name: Backend CI workflow

on:
    workflow_dispatch:
    pull_request: 
      branches: [main] # only PRs targeting the main branch
      paths:
        - 'starter/backend/**' # only when backend files are changed

jobs:
  lint:
    name:   Code lint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
         python-version: '3.10'

      - name: Install pipenv
        run: pip install pipenv
     
      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install
          pipenv install flake8 --dev

      - name: Lint code
        run: |
            cd starter/backend 
            pipenv run lint
          
  test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install

      - name: Run tests
        run: |
          cd starter/backend
          pipenv run test
        

  build:
    name: Build if tests and lint pass
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          cd starter/backend
          docker build --tag mp-backend:latest .

    