name: Backend CI workflow

on:
    workflow_dispatch:
    pull_request: 
      branches: [main] # only PRs targeting the main branch
      paths:
        - 'starter/backend/**' # only when frontend files are changed

jobs:
  lint:
    name:   Code lint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
     
      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install

      - name: Lint code
        run: |
            cd starter/backend 
            pipenv run lint
          # This will fail the job if ESLint finds any errors
  
  test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install

      - name: Run tests
        run: |
          cd starter/backend
          pipenv run test
        # Without CI=true, tests would run in watch mode, waiting for file changes and not exiting


  build:
    name: Build if tests and lint pass
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install

      - name: Build
        run: |
          cd starter/backend
          docker build --tag mp-backend:latest .

    