name: frontend CI workflow

env:
  REACT_APP_MOVIE_API_URL: http://localhost:5000

on:
  workflow_dispatch:
  pull_request: 
    branches: [main] # only PRs targeting the main branch
    paths:
      - 'starter/frontend/**' # only when frontend files are changed

jobs:
  lint:
    name: code lint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # download the code from the repo to runner

      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version-file: 'starter/frontend/.nvmrc'

      - name: Install dependencies
        run: |
          cd starter/frontend
          npm ci

      - name: Lint code
        run: |
          cd starter/frontend 
          npm run lint
        # This will fail the job if ESLint finds any errors

  test:
    name: unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # download the code from the repo to runner

      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version-file: 'starter/frontend/.nvmrc' 
        # Use the Node.js version specified in the .nvmrc file as input

      - name: Install dependencies
        run: |
          cd starter/frontend
          npm ci

      - name: Run tests
        run: |
          cd starter/frontend
          CI=true npm test
        # Without CI=true, tests would run in watch mode, waiting for file changes and not exiting

  build:
    name: build if tests and lint pass
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: build docker image
        run: |
          cd starter/frontend
          docker build --build-arg=REACT_APP_MOVIE_API_URL --tag=mp-frontend:latest .

      
    
